#!/usr/bin/env python
from __future__ import print_function
from github import Github
from os.path import expanduser
from datetime import datetime
from socket import setdefaulttimeout
setdefaulttimeout(120)
import os.environ

if __name__ == "__main__":
  gh = Github(os.environ['GITHUBTOKEN'])
  print('API Rate Limit')
  print('Limit, Remaining: ', gh.rate_limiting)
  print('Reset time (GMT): ', datetime.fromtimestamp(gh.rate_limiting_resettime))

